version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ".:/var/www/html"
    links:
      - database
      - mongo

  database:
    image: mysql:5.7
    restart: always
    container_name: my_sql
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
